version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file: ".env"

  flask_api:
    env_file: ".env"
    ports:
      - 5033:5000
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

  testing_postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    env_file: ".env"
    profiles: ["testing"]
