version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file: ".env"

  testing_postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    env_file: ".env"
    profiles: ["testing"]
